"use client";

import { useParams, useRouter } from "next/navigation";
import { useMemo, useState } from "react";

const translations={
  "en-US":{language:"English",title:"RO3 Pioneer Test Player Survey",intro:"Thank you for joining the pioneer test. This survey takes about 3–5 minutes.",q1:"How satisfied are you with your overall experience?",q2:"How likely are you to recommend this game to a friend?",q3:"What else can we improve?",choices:["Very satisfied","Satisfied","Neutral","Dissatisfied","Very dissatisfied"],next:"Next",back:"Back",submit:"Submit",placeholder:"Share any detail that would help us improve.",done:"Thank you for your feedback!",doneText:"Your response has been submitted successfully."},
  "zh-TW":{language:"繁體中文",title:"RO3 先鋒測試玩家體驗調研",intro:"感謝您參與本次先鋒測試，問卷預計需要 3–5 分鐘完成。",q1:"您對本次先鋒測試的整體體驗如何？",q2:"您有多大可能向朋友推薦這款遊戲？",q3:"還有哪些體驗可以改進？",choices:["非常滿意","滿意","一般","不滿意","非常不滿意"],next:"下一題",back:"返回",submit:"提交",placeholder:"請分享可以幫助我們改進的細節。",done:"感謝您的回饋！",doneText:"您的答卷已成功提交。"},
  "th-TH":{language:"ไทย",title:"แบบสำรวจประสบการณ์ผู้เล่น RO3",intro:"ขอบคุณที่เข้าร่วมการทดสอบ แบบสำรวจใช้เวลาประมาณ 3–5 นาที",q1:"คุณพึงพอใจกับประสบการณ์โดยรวมเพียงใด",q2:"คุณมีแนวโน้มที่จะแนะนำเกมนี้ให้เพื่อนมากน้อยเพียงใด",q3:"มีส่วนใดที่เราควรปรับปรุงเพิ่มเติม",choices:["พอใจมาก","พอใจ","ปานกลาง","ไม่พอใจ","ไม่พอใจมาก"],next:"ถัดไป",back:"กลับ",submit:"ส่ง",placeholder:"แบ่งปันรายละเอียดเพื่อช่วยเราปรับปรุง",done:"ขอบคุณสำหรับความคิดเห็น!",doneText:"ส่งคำตอบของคุณเรียบร้อยแล้ว"},
};

export default function PlayerSurvey(){
  const router=useRouter();const params=useParams<{slug:string}>();const [locale,setLocale]=useState<keyof typeof translations>("en-US");const [step,setStep]=useState(0);const [choice,setChoice]=useState("");const [nps,setNps]=useState<number|null>(null);const [feedback,setFeedback]=useState("");const [done,setDone]=useState(false);const [consent,setConsent]=useState(false);const text=translations[locale];const progress=useMemo(()=>done?100:step===0?10:(step/3)*100,[step,done]);
  if(done)return <main className="player-survey-shell"><div className="player-language"><span>RO3</span><select value={locale} onChange={(e)=>setLocale(e.target.value as keyof typeof translations)}>{Object.entries(translations).map(([key,value])=><option key={key} value={key}>{value.language}</option>)}</select></div><section className="player-complete"><span>✓</span><h1>{text.done}</h1><p>{text.doneText}</p><div><small>Response ID</small><strong>RSP-DEMO-{params.slug.slice(-4).toUpperCase()}</strong></div><button onClick={()=>router.push("/")}>返回演示后台</button></section></main>;
  return <main className="player-survey-shell"><div className="player-language"><span>RO3 · PLAYER RESEARCH</span><select value={locale} onChange={(e)=>setLocale(e.target.value as keyof typeof translations)}>{Object.entries(translations).map(([key,value])=><option key={key} value={key}>{value.language}</option>)}</select></div><div className="player-progress"><i style={{width:`${progress}%`}}/></div>
    <section className="player-survey-card">
      {step===0&&<div className="player-cover"><span>RO3 PIONEER TEST</span><h1>{text.title}</h1><p>{text.intro}</p><ul><li><i>◷</i>3–5 min</li><li><i>▤</i>3 questions</li><li><i>⌾</i>Global data region</li></ul><label><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)}/><span>I have read and agree to the privacy notice and understand how my responses will be used.</span></label><button disabled={!consent} onClick={()=>setStep(1)}>Start survey →</button></div>}
      {step===1&&<div className="player-question"><small>01 / 03 · SINGLE CHOICE</small><h2>{text.q1}<b>*</b></h2><p>Select one option</p><div className="player-options">{text.choices.map(item=><button key={item} className={choice===item?"selected":""} onClick={()=>setChoice(item)}><i>{choice===item?"●":"○"}</i>{item}</button>)}</div><footer><span>✓ Saved</span><button disabled={!choice} onClick={()=>setStep(2)}>{text.next} →</button></footer></div>}
      {step===2&&<div className="player-question"><small>02 / 03 · NPS</small><h2>{text.q2}<b>*</b></h2><p>0 = Not at all likely · 10 = Extremely likely</p><div className="player-nps">{Array.from({length:11},(_,i)=>i).map(score=><button key={score} className={nps===score?"selected":""} onClick={()=>setNps(score)}>{score}</button>)}</div><div className="nps-labels"><span>Not likely</span><span>Extremely likely</span></div><footer><button className="player-back" onClick={()=>setStep(1)}>← {text.back}</button><button disabled={nps===null} onClick={()=>setStep(3)}>{text.next} →</button></footer></div>}
      {step===3&&<div className="player-question"><small>03 / 03 · LONG TEXT</small><h2>{text.q3}</h2><p>Optional</p><textarea value={feedback} onChange={(e)=>setFeedback(e.target.value)} placeholder={text.placeholder} maxLength={1000}/><div className="text-count">{feedback.length} / 1000</div><footer><button className="player-back" onClick={()=>setStep(2)}>← {text.back}</button><button onClick={()=>setDone(true)}>{text.submit} ✓</button></footer></div>}
    </section><footer className="player-privacy">Privacy protected · Responses stored in the Global data region · Powered by JoyData Survey</footer>
  </main>
}
